# Generated by Django 5.0.2 on 2025-11-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_property_favourited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='favourited',
            new_name='favorited',
        ),
    ]
